<?php
namespace app\controllers;

use yii\web\Controller;

class BaseController extends Controller{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

}